//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class XL2Spectrum
    {
        public int Id { get; set; }
        public int XL2id { get; set; }
        public string FreqWeight { get; set; }
        public string TimeWeight { get; set; }
        public string Metric { get; set; }
        public string Hz6 { get; set; }
        public string Hz8 { get; set; }
        public string Hz10 { get; set; }
        public string Hz12 { get; set; }
        public string Hz16 { get; set; }
        public string Hz20 { get; set; }
        public string Hz25 { get; set; }
        public string Hz31 { get; set; }
        public string Hz50 { get; set; }
        public string Hz63 { get; set; }
        public string Hz80 { get; set; }
        public string Hz100 { get; set; }
        public string Hz125 { get; set; }
        public string Hz160 { get; set; }
        public string Hz200 { get; set; }
        public string Hz250 { get; set; }
        public string Hz315 { get; set; }
        public string Hz400 { get; set; }
        public string Hz40 { get; set; }
        public string Hz500 { get; set; }
        public string Hz630 { get; set; }
        public string Hz800 { get; set; }
        public string Hz1000 { get; set; }
        public string Hz1250 { get; set; }
        public string Hz1600 { get; set; }
        public string Hz2000 { get; set; }
        public string Hz2500 { get; set; }
        public string Hz3150 { get; set; }
        public string Hz4000 { get; set; }
        public string Hz5000 { get; set; }
        public string Hz6300 { get; set; }
        public string Hz8000 { get; set; }
        public string Hz10000 { get; set; }
        public string Hz12500 { get; set; }
        public string Hz16000 { get; set; }
        public string Hz20000 { get; set; }
        public string Overall { get; set; }
    
        public virtual XL2Table XL2 { get; set; }
    }
}
