//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class XL2Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XL2Table()
        {
            this.XL2Spectrum = new HashSet<XL2Spectrum>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTimeOfMeasurement { get; set; }
        public Nullable<System.DateTime> GPSStartTimeOfMeasurement { get; set; }
        public Nullable<System.DateTime> SensorStartTimeOfMeasurement { get; set; }
        public string SLMSerial { get; set; }
        public string MicType { get; set; }
        public string MeasureStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XL2Spectrum> XL2Spectrum { get; set; }
    }
}
