//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class XL2Table
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTimeOfMeasurement { get; set; }
        public Nullable<System.DateTime> GPSStartTimeOfMeasurement { get; set; }
        public Nullable<System.DateTime> SensorStartTimeOfMeasurement { get; set; }
        public string SLMSerial { get; set; }
        public string MicType { get; set; }
        public string MeasureStatus { get; set; }
        public string MicSens { get; set; }
    }
}
